Add currency field to the app visualization
layers-digital/layers-financeiro pull request #33
Opened 2023-03-03 20:09 UTC by tuliocaviquioli

Adiocionando a moeda para configurar a sigla no front do app.

2023-03-03 20:20 UTC, ramirezmz commented on web/src/components/PayableDetailCard.vue
> +  mounted() {
Voce pode remover o mounted e o console

2023-03-03 20:23 UTC, ramirezmz approved these changes

2023-03-03 20:23 UTC, guim4dev commented on web/src/helpers/currencyFormatter.js
> +  let integerValue = value / 100;
pq um let ?

2023-03-03 20:31 UTC, CarlosZoft requested changes

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/helpers/currencyFormatter.js
> +  let integerValue = value / 100;
essa váriavel não é integer na maioria dos casos

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/components/PayableDetailCard.vue
> +import currencyFormatter from '../helpers/currencyFormatter';
```suggestion
import currencyFormatter from '@/helpers/currencyFormatter';
```

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/views/PayableDetail.vue
> +import currencyFormatter from '../helpers/currencyFormatter';
```suggestion
import currencyFormatter from '@/helpers/currencyFormatter';
```

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/components/PayableDetailCard.vue
> +  },
```suggestion
```

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/components/PayableDetailCard.vue
>        <div class="ls-col mr-2 amount" :class="amountColor" v-if="payable.amountPaid">
```suggestion
      <div class="ls-col mr-2 amount" :class="amountColor" v-if="amountPaid">
```

2023-03-03 20:31 UTC, CarlosZoft commented on web/src/components/PayableDetailCard.vue
> +
Sugestão : 

Da pra criar uma computed que recebe só o valor. Daí envia só o value msm

```
 currencyFormatterFunc (value) {
    return currencyFormatter(value, this.payable.currency, navigator.language);
 }
```

2023-03-04 23:47 UTC, CarlosZoft approved these changes

2023-03-06 14:14 UTC, guim4dev approved these changes

2023-03-06 14:14 UTC, merged