Fix/code line payable
layers-digital/layers-financeiro pull request #38
Opened 2023-05-29 21:20 UTC by ramirezmz

# Descrição

Separando a função downloadBoletos para um helper e usando com condionais no PayableDetais e/ou Boletos

2023-05-29 21:30 UTC, guim4dev requested changes

2023-05-29 21:30 UTC, guim4dev commented on web/src/helpers/downloadBoleto.js
> +export default async function boletoDownload(url, title = '', type = '') {
```suggestion
export default async function downloadPayable(url, title = '', type = '') {
```

mudar tudo pra downloadPayable!

2023-05-29 21:30 UTC, guim4dev commented on web/src/views/PayableDetail.vue
> +import boletoDownload from '@/helpers/downloadBoleto';
```suggestion
import downloadPayable from '@/helpers/downloadPayable';
```

2023-05-29 21:30 UTC, guim4dev commented on web/src/views/PayableDetail.vue
> +    async openBoleto() {
tratar isso dentro do modal!

2023-05-31 13:37 UTC, ramirezmz commented on web/src/components/Modals/BoletoModal.vue
> +      <h2 v-if="codigo.boleto">Baixe o boleto ou copie o código para pagar</h2>
Eu acho que seria uma boa colocar numa computed `codigo.boleto`. Dessa forma você pode reutilizar na linha 16 também e caso precise de uma lógica, você modifica nela.
Além disso, caso seja modificado o chave valor codigo.boleto irá quebrar o front

2023-05-31 20:38 UTC, guim4dev commented on web/src/components/Modals/BoletoModal.vue
> +        <li v-if="boleto.code">Utilize o boleto ou o código abaixo:</li>
eh boleto.code ou codigo.boleto ?

2023-06-01 16:59 UTC, victorleonardi commented on web/src/components/Modals/BoletoModal.vue
> +        <li v-if="boleto.code">Utilize o boleto ou o código abaixo:</li>
boleto.code

2023-06-01 20:20 UTC, guim4dev commented on web/src/components/Modals/BoletoModal.vue
> +      <h2 v-else>Baixe o boleto para pagar</h2>
e se eu tiver o codigo do boleto mas nao tiver o arquivo ?

2023-06-02 12:21 UTC, ramirezmz commented on web/src/components/Modals/BoletoModal.vue
> +      <h2 v-else>Baixe o boleto para pagar</h2>
Acho que essa logica tem que estar numa computed

2023-06-02 15:39 UTC, guim4dev commented on web/src/components/Modals/BoletoModal.vue
> +      <h2 v-else>Baixe o boleto para pagar</h2>
concordo! tudo isso tem que ir pra uma computed de definicao de contexto, de forma a tratar os 3 casos

2023-06-02 20:42 UTC, merged